export const BALL_POOL_SOURCE = {
  codepen: 'https://codepen.io/mrdoob/pen/dPpJMXB',
  title: 'Ball Pool #2',
  author: 'mrdoob',
  threeVersion: '0.184.0',
  bounceVersion: '1.8.0',
};

export const BALL_POOL_DEFAULTS = {
  preset: 'codepen-original',
  paused: false,
  ballRadius: 0.4,
  fillRatio: 0.4,
  packing: 0.6,
  boxHeight: 6,
  boxDepth: 8,
  wallThickness: 0.5,
  cameraFov: 45,
  gravity: -9.81,
  restitution: 0.4,
  friction: 0.5,
  linearDamping: 0.1,
  angularDamping: 0.1,
  solveVelocityIterations: 6,
  solvePositionIterations: 2,
  glassRadius: 0.8,
  glassMass: 5,
  springStiffness: 500,
  springDamping: 40,
  pushRadius: 1.5,
  pushStrength: 5,
  lightIntensity: 80,
  easeSpeed: 8,
  toneMappingExposure: 0.35,
  giIntensity: 18,
  aoIntensity: 0.55,
  ssgiSliceCount: 2,
  ssgiStepCount: 8,
  bloomThreshold: 0.1,
  bloomStrength: 0.25,
  bloomRadius: 0,
  pixelRatio: 1.5,
};
