/**
 * Showcase.tsx — per-module showcase: live preview + inline auto-generated controls
 * (PANELFLOW), plus usage, dependencies, presets, related links, and agent notes.
 *
 * Registering the schema also surfaces the module's control panel in the dock rail
 * and command palette (PanelFlowProvider auto-generates it). The preview reads the
 * same bridge the controls write, so edits drive it within a frame (FR-11).
 */

import { Component, useEffect, useState, type ReactNode } from 'react';
import { ArrowLeft, Copy, Check, AlertTriangle } from 'lucide-react';
import {
  AutoGeneratedPanel,
  registerComponent,
  unregisterComponent,
  initializeBridgeDefaults,
  useBridgeStore,
} from '@artinos/panelflow';
import type { ArtinosModule } from '../registry/types';
import { useStudioStore } from '../studio-store';
import { getModule } from '../registry/registry';

export function Showcase({ module }: { module: ArtinosModule }) {
  const openGallery = useStudioStore((s) => s.openGallery);
  const openShowcase = useStudioStore((s) => s.openShowcase);
  const setAllParams = useBridgeStore((s) => s.setAllParams);
  // Stable boolean: are this module's bridge defaults loaded yet? Gate the
  // auto-panel on it so it never renders against an undefined slice (which would
  // make PANELFLOW's `componentValues[id] || {}` selector loop on getSnapshot).
  const ready = useBridgeStore((s) => module.id in s.componentValues);

  useEffect(() => {
    registerComponent(module.schema);
    initializeBridgeDefaults(module.schema);
    return () => unregisterComponent(module.id);
  }, [module.id, module.schema]);

  const Preview = module.preview;

  const applyPreset = (preset: Record<string, unknown>) => {
    const base: Record<string, unknown> = {};
    for (const p of module.schema.parameters) base[p.key] = p.default;
    setAllParams(module.id, { ...base, ...preset });
  };

  return (
    <div className="absolute inset-0 overflow-y-auto custom-scrollbar">
      <div className="mx-auto max-w-6xl px-8 pt-6 pb-[540px]">
        {/* Header (wraps on narrow widths) */}
        <div className="flex flex-wrap items-center gap-3 mb-6">
          <button
            onClick={openGallery}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg glass-panel border border-white/10 text-xs text-white/70 hover:text-white transition-colors shrink-0"
          >
            <ArrowLeft size={14} /> Library
          </button>
          <div className="flex items-center gap-3 min-w-0">
            <h1 className="text-xl font-bold truncate" style={{ color: 'var(--color-text)' }}>
              {module.name}
            </h1>
            <span
              className="text-[9px] uppercase tracking-[0.2em] px-2 py-1 rounded-md shrink-0"
              style={{ color: 'var(--color-accent)', background: 'rgba(45,212,191,0.1)' }}
            >
              {module.category}
            </span>
          </div>
          <div className="ml-auto shrink-0">
            <StatusBadge validation={module.validation} />
          </div>
        </div>

        {/* Live preview stage (responsive height, error-isolated) */}
        <div className="glass-panel rounded-2xl border border-white/10 overflow-hidden mb-6 h-[260px] sm:h-[320px] lg:h-[360px]">
          <div className="relative w-full h-full">
            <PreviewStage module={module} Preview={Preview} />
          </div>
        </div>

        {/* Controls + info */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Auto-generated controls (PANELFLOW) */}
          <section>
            <SectionTitle>Controls</SectionTitle>
            <div className="glass-panel rounded-xl border border-white/10 overflow-hidden" style={{ maxHeight: 440 }}>
              {ready ? (
                <AutoGeneratedPanel schema={module.schema} />
              ) : (
                <div className="p-4 text-[10px] uppercase tracking-widest text-white/30">Loading controls…</div>
              )}
            </div>
          </section>

          {/* Info column */}
          <section className="flex flex-col gap-6">
            {module.presets && Object.keys(module.presets).length > 0 && (
              <div>
                <SectionTitle>Presets</SectionTitle>
                <div className="flex flex-wrap gap-2">
                  {Object.entries(module.presets).map(([name, values]) => (
                    <button
                      key={name}
                      onClick={() => applyPreset(values)}
                      className="px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider rounded-md bg-black/40 border border-white/10 text-white/60 hover:bg-white/10 hover:text-white transition-all"
                    >
                      {name}
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div>
              <SectionTitle>Usage</SectionTitle>
              <CodeBlock code={module.usage} />
            </div>

            <div>
              <SectionTitle>Dependencies</SectionTitle>
              <div className="flex flex-wrap gap-1.5">
                {module.dependencies.map((d) => (
                  <span key={d} className="text-[10px] font-mono px-2 py-1 rounded bg-white/5 text-white/60">
                    {d}
                  </span>
                ))}
              </div>
            </div>

            {module.related && module.related.length > 0 && (
              <div>
                <SectionTitle>Related</SectionTitle>
                <div className="flex flex-wrap gap-2">
                  {module.related.map((id) => {
                    const exists = !!getModule(id);
                    return (
                      <button
                        key={id}
                        disabled={!exists}
                        onClick={() => exists && openShowcase(id)}
                        className={
                          'px-3 py-1.5 text-[10px] rounded-md border transition-all ' +
                          (exists
                            ? 'border-[var(--color-accent)]/40 text-white/80 hover:bg-[var(--color-accent)]/10'
                            : 'border-white/5 text-white/25 cursor-not-allowed')
                        }
                      >
                        {id}
                        {!exists && ' · not yet in library'}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            <div>
              <SectionTitle>Agent notes</SectionTitle>
              <p className="text-xs leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
                {module.agentNotes}
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}

// ── Preview isolation: error boundary + capability check (FR-13) ─────────────

function Notice({ children }: { children: ReactNode }) {
  return (
    <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 p-6 text-center">
      <AlertTriangle size={18} className="text-amber-400/80" />
      <p className="text-xs max-w-xs leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
        {children}
      </p>
    </div>
  );
}

class PreviewErrorBoundary extends Component<{ children: ReactNode }, { error: Error | null }> {
  state: { error: Error | null } = { error: null };
  static getDerivedStateFromError(error: Error) {
    return { error };
  }
  render() {
    if (this.state.error) {
      return <Notice>Preview failed to render: {this.state.error.message}</Notice>;
    }
    return this.props.children;
  }
}

function PreviewStage({ module, Preview }: { module: ArtinosModule; Preview: ArtinosModule['preview'] }) {
  const needsWebGPU = module.dependencies.includes('webgpu');
  const noWebGPU = needsWebGPU && typeof navigator !== 'undefined' && !('gpu' in navigator);
  if (noWebGPU) {
    return <Notice>This module requires WebGPU, which isn't available in this browser.</Notice>;
  }
  return (
    <PreviewErrorBoundary>
      <Preview />
    </PreviewErrorBoundary>
  );
}

function StatusBadge({ validation }: { validation?: { build: boolean; preview: boolean; console: boolean } }) {
  const verified = validation ? validation.build && validation.preview && validation.console : null;
  const color = verified === false ? '#f59e0b' : 'var(--color-accent)';
  const label = verified === null ? 'Running' : verified ? 'Verified' : 'Issues';
  return (
    <span className="flex items-center gap-1.5 text-[10px] uppercase tracking-widest text-white/50">
      <span className="w-1.5 h-1.5 rounded-full" style={{ background: color }} /> {label}
    </span>
  );
}

function SectionTitle({ children }: { children: ReactNode }) {
  return (
    <div className="text-[10px] uppercase tracking-[0.2em] mb-2.5" style={{ color: 'var(--color-text-soft, rgba(255,255,255,0.45))' }}>
      {children}
    </div>
  );
}

function CodeBlock({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* clipboard blocked — ignore */
    }
  };
  return (
    <div className="relative">
      <pre className="text-[11px] font-mono leading-relaxed bg-black/50 border border-white/10 rounded-lg p-3 overflow-x-auto text-white/80 whitespace-pre-wrap">
        {code}
      </pre>
      <button
        onClick={copy}
        className="absolute top-2 right-2 p-1.5 rounded-md bg-white/5 hover:bg-white/15 text-white/60 transition-colors"
        aria-label="Copy usage snippet"
      >
        {copied ? <Check size={13} /> : <Copy size={13} />}
      </button>
    </div>
  );
}
