/**
 * @artinos/panelflow — Public API Surface
 * 
 * This is the single entry point for the PANELFLOW package.
 * All exports are organized by subsystem.
 */

// ── Core Provider ─────────────────────────────────────────────────────────
export { PanelFlowProvider, type PanelFlowProviderProps } from './panel-os/PanelFlowProvider';

// ── Panel OS ──────────────────────────────────────────────────────────────
export { definePanel } from './panel-os/define-panel';
export { usePanelOSStore } from './panel-os/panel-store';
export { PANEL_REGISTRY, PANEL_DEFINITIONS, getPanelDefinition, registerPanel } from './panel-os/panel-registry';
export { PanelShell } from './panel-os/panel-shell';
export type { PanelDefinition, PanelCapabilities } from './panel-os/panel-types';
export type { DockMode, DockFloatRect } from './panel-os/panel-store';

// ── Shell Components ──────────────────────────────────────────────────────
export { EditorDock } from './shell/editor-dock';
export { IconRail, type IconRailProps } from './shell/icon-rail';
export { PanelChrome } from './shell/panel-chrome';
export { CommandPalette, openPanelById } from './shell/command-palette';
export { ViewportSlot, type ViewportSlotProps } from './shell/viewport-slot';

// ── Graph Canvas ──────────────────────────────────────────────────────────
export { GraphCanvas } from './graph/graph-canvas';
export { useGraphStore, hydrateGraph, resetWorkspace } from './graph/graph-store';
export { UniversalNode } from './graph/universal-node';
export { OSPanelNode } from './graph/os-panel-node';
export { DotGridBackground } from './graph/dot-grid-background';
export type { FluidityNode, FluidityNodeData, FluidityEdge, SceneSettings, StatsState } from './graph/graph-store';

// ── Control Panel Engine ──────────────────────────────────────────────────
export {
  registerComponent,
  unregisterComponent,
  getRegisteredComponents,
  generatePanelFromSchema,
  useBridgeStore,
  initializeBridgeDefaults,
} from './control-engine';
export type {
  ComponentSchema,
  ParameterDef,
  ModifierDef,
  ControlBridge,
} from './control-engine';

// ── Auto-Generated Panels ─────────────────────────────────────────────────
export { AutoGeneratedPanel } from './panels/auto-panel';

// ── Tweakpane Frost ───────────────────────────────────────────────────────
export { useFrostPane } from './lib/tweakpane_frost/useFrostPane';
export { FrostPanePanel, type FrostPanePanelProps } from './lib/tweakpane_frost/FrostPanePanel';

// ── Design System ─────────────────────────────────────────────────────────
export { THEME, token, injectTheme } from './studio-theme';

// ── Component Library ─────────────────────────────────────────────────────
export { GooeySlider } from './components/GooeySlider';
export { BubbleRatingSlider } from './components/BubbleRatingSlider';
export { ElasticMenu } from './components/ElasticMenu';
export { Tooltip } from './components/ui/tooltip';

// ── Workspace (Demo / Full Layout) ────────────────────────────────────────
export { Workspace } from './workspace';
