/**
 * @artinos/panelflow — Public API Surface
 * 
 * This is the single entry point for the PANELFLOW package.
 * All exports are organized by subsystem.
 */

// ── Core Provider ─────────────────────────────────────────────────────────
export { PanelFlowProvider, type PanelFlowProviderProps } from './panel-os/PanelFlowProvider';

// ── Panel OS ──────────────────────────────────────────────────────────────
export { definePanel } from './panel-os/define-panel';
export { usePanelOSStore } from './panel-os/panel-store';
export { PANEL_REGISTRY, PANEL_DEFINITIONS, getPanelDefinition, registerPanel } from './panel-os/panel-registry';
export { PanelShell } from './panel-os/panel-shell';
export type { PanelDefinition, PanelCapabilities } from './panel-os/panel-types';
export type { DockMode, DockFloatRect } from './panel-os/panel-store';

// ── Shell Components ──────────────────────────────────────────────────────
export { EditorDock, type EditorDockBrand, type EditorDockProps } from './shell/editor-dock';
export { IconRail, type IconRailProps } from './shell/icon-rail';
export { PanelChrome } from './shell/panel-chrome';
export { CommandPalette, openPanelById } from './shell/command-palette';
export { ViewportSlot, type ViewportSlotProps } from './shell/viewport-slot';

// ── Graph Canvas ──────────────────────────────────────────────────────────
export { GraphCanvas } from './graph/graph-canvas';
export { useGraphStore, hydrateGraph, resetWorkspace } from './graph/graph-store';
export {
  publishPerformanceStats,
  resetPerformanceStats,
  usePerformanceTelemetry,
  type PerformanceStatsPatch,
} from './performance-telemetry';
export { registerNode, defineNode, getNode, allNodes } from './graph/NodeDefinitions';
export type { NodeDefinition, NodeDomain, PortType, Port, Param } from './graph/NodeDefinitions';
export { registerRuntimeNode, NODE_REGISTRY, getNodeDef, makeNode } from './graph/node-registry';
export { UniversalNode } from './graph/universal-node';
export { OSPanelNode } from './graph/os-panel-node';
export { DotGridBackground } from './graph/dot-grid-background';
export type { FluidityNode, FluidityNodeData, FluidityEdge, SceneSettings, StatsState } from './graph/graph-store';

// ── Control Panel Engine ──────────────────────────────────────────────────
export {
  registerComponent,
  unregisterComponent,
  registerComponentInstance,
  unregisterComponentInstance,
  getRegisteredComponents,
  getRegisteredComponentInstances,
  getComponentSchema,
  generatePanelFromSchema,
  useBridgeStore,
  initializeBridgeDefaults,
} from './control-engine';
export type {
  ComponentSchema,
  ComponentInstance,
  RegisterComponentInstanceOptions,
  ParameterDef,
  ModifierDef,
  ControlBridge,
} from './control-engine';

// ── Control System (dynamic, schema-driven) ───────────────────────────────
export { ControlPanel, type ControlPanelProps } from './controls/ControlPanel';

// ── Auto-Generated Panels (legacy) ────────────────────────────────────────
export { AutoGeneratedPanel } from './panels/auto-panel';

// ── Tweakpane Frost (legacy) ──────────────────────────────────────────────
export { useFrostPane } from './lib/tweakpane_frost/useFrostPane';
export { FrostPanePanel, type FrostPanePanelProps } from './lib/tweakpane_frost/FrostPanePanel';

// ── Design System ─────────────────────────────────────────────────────────
export { THEME, token, injectTheme } from './studio-theme';

// ── UI Kit (shadcn/Radix, themed) ─────────────────────────────────────────
export { Slider } from './components/ui/slider';
export { Switch } from './components/ui/switch';
export { Input } from './components/ui/input';
export { Label } from './components/ui/label';
export { Separator } from './components/ui/separator';
export { ScrollArea } from './components/ui/scroll-area';
export { ColorField } from './components/ui/color-field';
export { ToggleGroup, ToggleGroupItem } from './components/ui/toggle-group';
export { Collapsible, CollapsibleTrigger, CollapsibleContent } from './components/ui/collapsible';
export { Popover, PopoverTrigger, PopoverContent, PopoverAnchor } from './components/ui/popover';
export {
  Select,
  SelectValue,
  SelectGroup,
  SelectTrigger,
  SelectContent,
  SelectItem,
} from './components/ui/select';
export { IconButton, type IconButtonProps } from './components/ui/icon-button';

// ── Component Library ─────────────────────────────────────────────────────
export { GooeySlider } from './components/GooeySlider';
export { BubbleRatingSlider } from './components/BubbleRatingSlider';
export { ElasticMenu } from './components/ElasticMenu';
export { Tooltip } from './components/ui/tooltip';

// ── Workspace (Demo / Full Layout) ────────────────────────────────────────
export { Workspace } from './workspace';
